spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

jwt_secret: netology
file:
  storage:
    location: ${user.dir}/storage

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG